// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check2FACode(arg1, arg2) {
  return window['go']['main']['App']['Check2FACode'](arg1, arg2);
}

export function RegisterOrLogin(arg1) {
  return window['go']['main']['App']['RegisterOrLogin'](arg1);
}

export function Send2FACode(arg1) {
  return window['go']['main']['App']['Send2FACode'](arg1);
}

export function UpdateUsername(arg1, arg2) {
  return window['go']['main']['App']['UpdateUsername'](arg1, arg2);
}
