// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Check2FACode(arg1:string,arg2:string):Promise<boolean>;

export function RegisterOrLogin(arg1:string):Promise<backend.User>;

export function Send2FACode(arg1:string):Promise<void>;
